export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const FACEBOOK_SIGN_IN_START = 'FACEBOOK_SIGN_IN_START';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const FETCH_TO_DOS_START = 'FETCH_TO_DOS_START';
export const FETCH_TO_DOS_SUCCESS = 'FETCH_TO_DOS_SUCCESS';
export const FETCH_TO_DOS_FAILURE = 'FETCH_TO_DOS_FAILURE';

export const ADD_TO_DO = 'ADD_TO_DO';
export const ADD_TO_DO_FAILURE = 'ADD_TO_DO_FAILURE';

export const COMPLETE_TO_DO = 'COMPLETE_TO_DO';
export const DELETE_TO_DO = 'DELETE_TO_DO';
export const UPDATE_TO_DO = 'UPDATE_TO_DO';
